export const cats = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
  },
  {
    id: 11,
    name: "Lenna Hert",
    username: "Lhine",
    email: "lennaheart@hert.io",
  },
  {
    id: 12,
    name: "Tina DuBuque",
    username: "KristinaJanai",
    email: "tinadu@tina.biz",
  },
  {
    id: 13,
    name: "Hououin Kyouma",
    username: "Mad Scientist",
    email: "kyouma001@okarin.io",
  },
  {
    id: 14,
    name: "Klaus Schmidt",
    username: "Klaus",
    email: "klaus@schimdt.com",
  },
  {
    id: 15,
    name: "Glenna Dert",
    username: "Spacegirl69",
    email: "glennadert@glen.io",
  },
  {
    id: 16,
    name: "Rick Sanchez",
    username: "Sick Rick",
    email: "sanchez@rick.biz",
  },
  {
    id: 17,
    name: "Reiner Braun",
    username: "Armored Titan",
    email: "reina@dana.io",
  },
  {
    id: 18,
    name: "Lelouch Lamperouge",
    username: "Zero",
    email: "lulu@zero.dev",
  },
  {
    id: 19,
    name: "Christina C.",
    username: "CC",
    email: "cc@c.io",
  },
  {
    id: 20,
    name: "Quinn Fabray",
    username: "Quinnao",
    email: "quinn@fabray.biz",
  },
];
